server:
  port: 8877

spring:
  application:
    name: mall411

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


  thymeleaf:
    cache: false


mybatis-plus:
  mapper-locations: classpath:mapper/mall/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输入打印的sql语句



