server:
  port: 8877

spring:
  application:
    name: mall411

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  devtools:
    restart:
      enabled: true

  freemarker:
    cache: false

  jackson:
    time-zone: GMT+8

  thymeleaf:
    cache: false
  redis:
    host: 8.136.182.114
    port: 6379
    database: 1
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath:mapper/mall/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输入打印的sql语句


swagger:
  basePackage: com.wyl.mall.controller
  title: mall411
  description: 毕业设计
  version: V1.0
  author: calf


